///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) 2007, 2010 Michael A. Jackson for BlueQuartz Software
//  All rights reserved.
//  BSD License: http://www.opensource.org/licenses/bsd-license.html
//
//  This code was written under United States Air Force Contract number
//                           F33615-03-C-5220
//
///////////////////////////////////////////////////////////////////////////////
#ifndef ZEISSTAGMAPPING_H_
#define ZEISSTAGMAPPING_H_


#include "ZeissImport/ZeissXml/ZeissMetaFactory.h"

#include "DREAM3DLib/DREAM3DLib.h"
#include "DREAM3DLib/Common/DREAM3DSetGetMacros.h"

#include <map>

typedef QMap<int, QString>  ZeissIdNameMap;
typedef QMap<QString, int>  ZeissNameIdMap;
typedef QMap<int, ZeissMetaFactory::Pointer> ZeissFactoryMap;

/**
* @class ZeissTagMapping ZeissTagMapping.h R3D/Common/ZeissTagMapping.h
* @brief This class is used to map values from the Zeiss XML file to and from
* human readable values. It also creates factories for each of the tags found in the
* Zeiss XML file. For each value there is a const QString and an integer value
* that uniquely identifies the tag.
* @author Michael A. Jackson for BlueQuartz Software
* @date Jul 29, 2009
* @version 1.0
*/
class ZeissTagMapping
{
  public:
    DREAM3D_SHARED_POINTERS(ZeissTagMapping)

    virtual ~ZeissTagMapping();

    static ZeissTagMapping::Pointer instance();


    QString nameForId(int idtag);
    int idForName(const QString &name);
    ZeissMetaFactory::Pointer factoryForId(int idTag);
    AbstractZeissMetaData::Pointer metaDataForId(int idTag, const QString &value);
    AbstractZeissMetaData::Pointer metaDataForTagName(const QString &name);

  protected:
    ZeissTagMapping();

    void initIdNameMap();
    void initNameIdMap();
    void initFactoryMap();

  private:
    ZeissIdNameMap _idNameMap;
    ZeissNameIdMap _nameIdMap;
    ZeissFactoryMap _idFactoryMap;


    ZeissTagMapping(const ZeissTagMapping&);    // Copy Constructor Not Implemented
    void operator=(const ZeissTagMapping&);  // Operator '=' Not Implemented

};

namespace Zeiss
{
  namespace MetaXML
  {

    static const int ImageDataMappingTableId = 257;
    static const int ImageDataMappingLowId = 258;
    static const int ImageDataMappingHighId = 259;
    static const int ImageDataMappingAutoRangeId = 260;
    static const int DocumentThumbnailId = 261;
    static const int ImageDataMappingGammaId = 262;
    static const int ImageDataHistoMaxId = 263;
    static const int ImageOverExposureId = 264;
    static const int ImageRelativeTimeFirstId = 265;
    static const int ImageRelativeTime1Id = 265;
    static const int ImageRelativeTime2Id = 266;
    static const int ImageRelativeTime3Id = 267;
    static const int ImageRelativeTime4Id = 268;
    static const int ImageRelativeTimeId = 300;
    static const int ImageBaseTimeFirstId = 301;
    static const int ImageBaseTime1Id = 301;
    static const int ImageBaseTime2Id = 302;
    static const int ImageBaseTime3Id = 303;
    static const int ImageBaseTime4Id = 304;
    static const int ImageBaseTimeLast_reservedId = 332;
    static const int ImageObjectTypeId = 513;
    static const int ImageWidthId = 515;
    static const int ImageHeightId = 516;
    static const int ImageCountRawId = 517;
    static const int ImagePixelTypeId = 518;
    static const int CountId = 519;
    static const int CompressionFactorForSaveId = 521;
    static const int DocumentSaveFlagsId = 522;
    static const int ImageTimestampCommentsId = 523;
    static const int DocumentSubTypeId = 530;
    static const int CameraImageValidBitsPerPixelId = 531;
    static const int ImageMemoryUsageId = 532;
    static const int ImageMSBShiftForPixelsId = 533;
    static const int ScaleFactorForWidthId = 769;
    static const int ScaleTypeForWidthId = 770;
    static const int ScaleWidthId = 771;
    static const int ScaleFactorForHeightId = 772;
    static const int ScaleTypeForHeightId = 773;
    static const int ScaleHeightId = 774;
    static const int ScaleFactorForDepthId = 775;
    static const int ScaleTypeForDepthId = 776;
    static const int ScaleDepthId = 777;
    static const int ScalingParentId = 778;
    static const int EventLogTypeId = 1000;
    static const int EventLogDateId = 1001;
    static const int EventLogCodeId = 1002;
    static const int EventLogSourceNameId = 1003;
    static const int EventLogMessageId = 1004;
    static const int AcquisitionGroupId = 1024;
    static const int CameraImageAcquisitionTimeId = 1025;
    static const int CameraValidBitsPerPixelId = 1027;
    static const int MonoReferenceLowId = 1029;
    static const int MonoReferenceHighId = 1030;
    static const int RedReferenceLowId = 1031;
    static const int RedReferenceHighId = 1032;
    static const int GreenReferenceLowId = 1033;
    static const int GreenReferenceHighId = 1034;
    static const int BlueReferenceLowId = 1035;
    static const int BlueReferenceHighId = 1036;
    static const int GrabberNameId = 1041;
    static const int CameraNameId = 1042;
    static const int CameraTriggerSignalTypeId = 1044;
    static const int CameraTriggerEnableId = 1045;
    static const int GrabberTimeoutId = 1046;
    static const int AcquisitionTimeInDoubleId = 1047;
    static const int MultiChannelEnabledId = 1281;
    static const int MultiChannelColorId = 1282;
    static const int MultiChannelWeightId = 1283;
    static const int MultiChannelNameId = 1284;
    static const int DocumentInformationGroupId = 1536;
    static const int DocumentTitleId = 1537;
    static const int DocumentAuthorId = 1538;
    static const int DocumentKeywordsId = 1539;
    static const int DocumentCommentsId = 1540;
    static const int DocumentSampleIDId = 1541;
    static const int DocumentSubjectId = 1542;
    static const int RevisionNumberId = 1543;
    static const int DocumentPathId = 1544;
    static const int FileLinkId = 1545;
    static const int DocumentTypeId = 1546;
    static const int FileMediumId = 1547;
    static const int FileIDId = 1548;
    static const int DocumentFileNameId = 1549;
    static const int FileDateId = 1550;
    static const int FileSizeId = 1551;
    static const int DocumentNameId = 1553;
    static const int FileAttributesId = 1554;
    static const int ProjectGroupId = 1792;
    static const int DateId = 1793;
    static const int DocumentLastSavedById = 1794;
    static const int UserCompanyId = 1795;
    static const int UserCompanyLogoId = 1796;
    static const int ImageId = 1797;
    static const int UserIdId = 1800;
    static const int UserNameId = 1801;
    static const int UserCityId = 1802;
    static const int UserAddressId = 1803;
    static const int UserStateId = 1804;
    static const int UserPhoneId = 1805;
    static const int UserFaxId = 1806;
    static const int ObjectiveId = 2049;
    static const int OptovarId = 2050;
    static const int ReflectorId = 2051;
    static const int CondenserContrastId = 2052;
    static const int TransmissionFilter1Id = 2053;
    static const int TransmittedLightFilter1Id = 2053;
    static const int TransmissionFilter2Id = 2054;
    static const int TransmittedLightFilter2Id = 2054;
    static const int InternalShutterId = 2055;
    static const int ReflectedLightShutterId = 2055;
    static const int CondenserFrontlensId = 2056;
    static const int ExcitationFilterId = 2057;
    static const int TransmittedLightFieldstopId = 2060;
    static const int ReflectedLightApertureId = 2061;
    static const int CondenserNAId = 2062;
    static const int LightPathId = 2063;
    static const int HalogenLampOnId = 2064;
    static const int HalogenLampModeId = 2065;
    static const int HalogenLampVoltageId = 2066;
    static const int FluoLampModeId = 2068;
    static const int FluoLampIntensityId = 2069;
    static const int LightmanagerEnabledId = 2070;

    static const int FocusPositionId = 2072;
    static const int ImageCoordinateUId = 2073;
    //static const int StageXPositionId = 2073;
    static const int ImageCoordinateVId = 2074;
    //static const int StageYPositionId = 2074;
    static const int MicroscopeNameId = 2075;
    static const int ObjectiveMagnificationId = 2076;
    static const int ObjectiveNAId = 2077;
    static const int MicroscopeIlluminationId = 2078;
    static const int ExtraShutter1Id = 2079;
    static const int ExtraShutter2Id = 2080;
    static const int ExtraShutter3Id = 2081;
    static const int ExtraFilter1Id = 2082;
    static const int ExtraFilter2Id = 2083;
    static const int ParfocalCorrectionId = 2084;
    static const int ExtraShutter4Id = 2086;
    static const int ExtraShutter5Id = 2087;
    static const int ExtraShutter6Id = 2088;
    static const int ExtraFilter3Id = 2089;
    static const int ExtraFilter4Id = 2090;
    static const int ObjectivePositionId = 2103;
    static const int ObjectiveContrastMethodId = 2104;
    static const int ObjectiveImmersionTypeId = 2105;
    static const int ReflectorPositionId = 2107;
    static const int TransmissionFilter1PositionId = 2109;
    static const int TransmittedLightFilter1PositionId = 2109;
    static const int TransmissionFilter2PositionId = 2110;
    static const int TransmittedLightFilter2PositionId = 2110;
    static const int ExcitationFilterPositionId = 2112;
    static const int LampMirrorPositionId = 2113;
    static const int ExtraFilter1PositionId = 2114;
    static const int ExtraFilter2PositionId = 2115;
    static const int ExtraFilter3PositionId = 2116;
    static const int ExtraFilter4PositionId = 2117;
    static const int LightmanagerModeId = 2118;
    static const int HalogenLampCalibratedId = 2119;
    static const int CondenserNAGoSpeedId = 2120;
    static const int TransmittedLightFieldstopGoSpeedId = 2121;
    static const int OptovarGoSpeedId = 2122;
    static const int FocusCalibratedId = 2123;
    static const int FocusBasicPositionId = 2124;
    static const int FocusPowerId = 2125;
    static const int FocusBacklashId = 2126;
    static const int FocusMeasurementOriginId = 2127;
    static const int FocusMeasurementDistanceId = 2128;
    static const int FocusSpeedId = 2129;
    static const int FocusGoSpeedId = 2130;
    static const int FocusStepDistanceId = 2131;
    static const int FocusInitPositionId = 2132;
    static const int StageCalibratedId = 2133;
    static const int StagePowerId = 2134;
    static const int StageXBacklashId = 2135;
    static const int StageYBacklashId = 2136;
    static const int StageXSpeedId = 2137;
    static const int StageYSpeedId = 2138;
    static const int StageSpeedId = 2139;
    static const int StageXGoSpeedId = 2140;
    static const int StageYGoSpeedId = 2141;
    static const int StageXStepDistanceId = 2142;
    static const int StageYStepDistanceId = 2143;
    static const int StageXInitPositionId = 2144;
    static const int StageYInitPositionId = 2145;
    static const int MicroscopeMagnificationId = 2146;
    static const int ReflectorMagnificationId = 2147;
    static const int LampMirrorSelectionId = 2148;
    static const int FocusDepthId = 2149;
    static const int MicroscopeTypeId = 2150;
    static const int ObjectiveWorkingDistanceId = 2151;
    static const int ReflectedLightApertureGoSpeedId = 2152;
    static const int ExternalShutterId = 2153;
    static const int ObjectiveImmersionStopActiveId = 2154;
    static const int FocusStartSpeedId = 2155;
    static const int FocusAccelerationId = 2156;
    static const int ReflectedLightFieldstopId = 2157;
    static const int ReflectedLightFieldstopGoSpeedId = 2158;
    static const int ReflectedLightFilter1Id = 2159;
    static const int ReflectedLightFilter2Id = 2160;
    static const int ReflectedLightFilter1PositionId = 2161;
    static const int ReflectedLightFilter2PositionId = 2162;
    static const int TransmittedLightAttenuatorId = 2163;
    static const int ReflectedLightAttenuatorId = 2164;
    static const int TransmittedLightShutterId = 2165;
    static const int TransmittedLightAttenuatorGoSpeedId = 2166;
    static const int ReflectedLightAttenuatorGoSpeedId = 2167;
    static const int ApotomeFocusPositionId = 2168;
    static const int ApotomeFocusGoSpeedId = 2169;
    static const int ApotomePhasePositionId = 2170;
    static const int ApotomeSliderPositionId = 2171;
    static const int ApotomeGridLinesPerMillimeterId = 2172;
    static const int ApotomeWobbleMinPositionId = 2173;
    static const int ApotomeWobbleMaxPositionId = 2174;
    static const int ApotomeWobbleSpeedId = 2175;
    static const int TransmittedLightVirtualFilterPositionId = 2176;
    static const int TransmittedLightVirtualFilterId = 2177;
    static const int ReflectedLightVirtualFilterPositionId = 2178;
    static const int ReflectedLightVirtualFilterId = 2179;
    static const int ReflectedLightHALModeId = 2180;
    static const int ReflectedLightHALVoltageId = 2181;
    static const int ReflectedLightHALColourTemperatureId = 2182;
    static const int ContrastmanagerModeId = 2183;
    static const int DazzleProtectionId = 2184;
    static const int StageXCalibratedId = 2185;
    static const int StageYCalibratedId = 2186;
    static const int StageXPowerId = 2187;
    static const int StageYPowerId = 2188;
    static const int StageXStartSpeedId = 2189;
    static const int StageYStartSpeedId = 2190;
    static const int StageXAccelerationId = 2191;
    static const int StageYAccelerationId = 2192;
    static const int StageStartSpeedId = 2193;
    static const int StageAccelerationId = 2194;
    static const int ZoomId = 2195;
    static const int ZoomGoSpeedId = 2196;
    static const int LightZoomId = 2197;
    static const int LightZoomGoSpeedId = 2198;
    static const int LightZoomCoupledId = 2199;
    static const int TransmittedLightHALModeId = 2200;
    static const int TransmittedLightHALVoltageId = 2201;
    static const int TransmittedLightHALColourTemperatureId = 2202;
    static const int ReflectedLightCLModeId = 2203;
    static const int ReflectedLightCLIntensityId = 2204;
    static const int ReflectedLightCLColourTemperatureId = 2205;
    static const int TransmittedLightCLModeId = 2206;
    static const int TransmittedLightCLIntensityId = 2207;
    static const int TransmittedLightCLColourTemperatureId = 2208;
    static const int InfinitySpaceChangerPositionId = 2209;
    static const int SidePortPercentId = 2210;
    static const int TwoTvVisCamChangerPositionId = 2211;
    static const int OcularPercentId = 2212;
    static const int TwoTvCamerasChangerPositionId = 2213;
    static const int TopPortPercentId = 2214;
    static const int OcularShutterId = 2215;
    static const int TwoTvCamerasChangerCubeId = 2216;
    static const int LightWaveLengthId = 2217;
    static const int OcularMagnificationId = 2218;
    static const int CameraAdapterMagnificationId = 2219;
    static const int MicroscopePortId = 2220;
    static const int OcularTotalMagnificationId = 2221;
    static const int FieldOfViewId = 2222;
    static const int OcularId = 2223;
    static const int CameraAdapterId = 2224;
    static const int StageJoystickEnabledId = 2225;
    static const int ContrastmanagerContrastMethodId = 2226;
    static const int StageXJoystickEnabledId = 2227;
    static const int StageYJoystickEnabledId = 2228;

    static const int CameraFrameLeftId = 2307;
    static const int CameraFrameTopId = 2308;
    static const int CameraFrameWidthId = 2309;
    static const int CameraFrameHeightId = 2310;
    static const int CameraFrameBinningId = 2311;
    static const int CameraFrameFullId = 2312;
    static const int CameraFramePixelDistanceId = 2313;
    static const int DataFormatUseScalingId = 2318;
    static const int CameraFrameImageOrientationId = 2319;
    static const int MeteorChannelInputId = 2322;
    static const int MeteorChannelSyncId = 2323;
    static const int CameraWhiteBalanceRedId = 2325;
    static const int CameraWhiteBalanceGreenId = 2326;
    static const int CameraWhiteBalanceBlueId = 2327;
    static const int CameraFrameScalingFactorId = 2331;
    static const int MeteorCameraTypeId = 2562;
    static const int CameraExposureTimeValueId = 2564;
    static const int CameraExposureTimeAutoCalculateId = 2568;
    static const int MeteorGainValueId = 2569;
    static const int MeteorGainAutomaticId = 2571;
    static const int MeteorAdjustHueId = 2572;
    static const int MeteorAdjustSaturationId = 2573;
    static const int MeteorAdjustRedLowId = 2574;
    static const int MeteorAdjustGreenLowId = 2575;
    static const int MeteorAdjustBlueLowId = 2576;
    static const int MeteorAdjustRedHighId = 2577;
    static const int MeteorAdjustGreenHighId = 2578;
    static const int MeteorAdjustBlueHighId = 2579;
    static const int MeteorAdjustWhiteRefEnableId = 2580;
    static const int CameraExposureTimeCalculationControlId = 2582;
    static const int AxioCamFadingCorrectionEnableId = 2585;
    static const int AxioCamSuspendLiveTimeoutId = 2586;
    static const int CameraLiveImageId = 2587;
    static const int CameraLiveEnabledId = 2588;
    static const int LiveImageSyncObjectNameId = 2589;
    static const int CameraLiveSpeedId = 2590;
    static const int CameraImageId = 2591;
    static const int CameraImageWidthId = 2592;
    static const int CameraImageHeightId = 2593;
    static const int CameraImagePixelTypeId = 2594;
    static const int CameraImageShMemoryNameId = 2595;
    static const int CameraLiveImageWidthId = 2596;
    static const int CameraLiveImageHeightId = 2597;
    static const int CameraLiveImagePixelTypeId = 2598;
    static const int CameraLiveImageShMemoryNameId = 2599;
    static const int CameraLiveMaximumSpeedId = 2600;
    static const int CameraLiveBinningId = 2601;
    static const int CameraLiveGainValueId = 2602;
    static const int CameraLiveExposureTimeValueId = 2603;
    static const int CameraLiveScalingFactorId = 2604;
    static const int CameraCoAcqFastModeId = 2605;
    static const int ImageIndexUId = 2817;
    static const int ImageIndexVId = 2818;
    static const int ImageIndexZId = 2819;
    static const int ImageIndexCId = 2820;
    static const int ImageIndexTId = 2821;
    static const int ImageIndexPId = 2822;
    static const int ImageIndexAId = 2823;
    static const int ImageCountPId = 2824;
    static const int ImageCountAId = 2825;
    static const int ImageIndexSId = 2827;
    static const int ImageIndexRawId = 2828;
    static const int ImageCountZId = 2832;
    static const int ImageCountCId = 2833;
    static const int ImageCountTId = 2834;
    static const int ImageCountUId = 2838;
    static const int ImageCountVId = 2839;
    static const int ImageCountSId = 2840;
    static const int ImageOrgCoordinateUId = 2841;
    static const int ImageOrgCoordinateVId = 2842;
    static const int LayerDrawFlagsId = 3088;
    static const int JobGroupId = 3328;
    static const int JobNameId = 3329;
    static const int JobInfoId = 3330;
    static const int JobProgressId = 3331;
    static const int JobStatusId = 3332;
    static const int JobIdId = 3333;
    static const int JobRemainingTimeId = 3334;
    static const int RelFocusPosition1Id = 333;
    static const int RelFocusPosition2Id = 334;
    static const int RelFocusPositionId = 2071;
    static const int SidePortTurretpositionId = 2252;
    static const int SidePortLeftPercentId = 2253;
    static const int SidePortRightPercentId = 2254;
    static const int BasePortSliderPortPercentId = 2255;
    static const int SidePortLeftFunctionId = 2256;
    static const int SidePortRightFunctionId = 2257;
    static const int BasePortSliderPortFunctionId = 2258;
    static const int SidePortLightPathId = 2259;
    static const int SidePortLightPathIDId = 2260;
    static const int ObjectiveIDId = 2261;
    static const int ReflectorIDId = 2262;

    const QString ImageDataMappingTable ("ImageDataMappingTable");
    const QString ImageDataMappingLow ("ImageDataMappingLow");
    const QString ImageDataMappingHigh ("ImageDataMappingHigh");
    const QString ImageDataMappingAutoRange ("ImageDataMappingAutoRange");
    const QString DocumentThumbnail ("DocumentThumbnail");
    const QString ImageDataMappingGamma ("ImageDataMappingGamma");
    const QString ImageDataHistoMax ("ImageDataHistoMax");
    const QString ImageOverExposure ("ImageOverExposure");
    const QString ImageRelativeTimeFirst ("ImageRelativeTimeFirst");
    const QString ImageRelativeTime1 ("ImageRelativeTime1");
    const QString ImageRelativeTime2 ("ImageRelativeTime2");
    const QString ImageRelativeTime3 ("ImageRelativeTime3");
    const QString ImageRelativeTime4 ("ImageRelativeTime4");
    const QString ImageRelativeTime ("ImageRelativeTime");
    const QString ImageBaseTimeFirst ("ImageBaseTimeFirst");
    const QString ImageBaseTime1 ("ImageBaseTime1");
    const QString ImageBaseTime2 ("ImageBaseTime2");
    const QString ImageBaseTime3 ("ImageBaseTime3");
    const QString ImageBaseTime4 ("ImageBaseTime4");
    const QString ImageBaseTimeLast_reserved ("ImageBaseTimeLast_reserved");
    const QString ImageObjectType ("ImageObjectType");
    const QString ImageWidth ("ImageWidth");
    const QString ImageHeight ("ImageHeight");
    const QString ImageCountRaw ("ImageCountRaw");
    const QString ImagePixelType ("ImagePixelType");
    const QString Count ("Count");
    const QString CompressionFactorForSave ("CompressionFactorForSave");
    const QString DocumentSaveFlags ("DocumentSaveFlags");
    const QString ImageTimestampComments ("ImageTimestampComments");
    const QString DocumentSubType ("DocumentSubType");
    const QString CameraImageValidBitsPerPixel ("CameraImageValidBitsPerPixel");
    const QString ImageMemoryUsage ("ImageMemoryUsage");
    const QString ImageMSBShiftForPixels ("ImageMSBShiftForPixels");
    const QString ScaleFactorForWidth ("ScaleFactorForWidth");
    const QString ScaleTypeForWidth ("ScaleTypeForWidth");
    const QString ScaleWidth ("ScaleWidth");
    const QString ScaleFactorForHeight ("ScaleFactorForHeight");
    const QString ScaleTypeForHeight ("ScaleTypeForHeight");
    const QString ScaleHeight ("ScaleHeight");
    const QString ScaleFactorForDepth ("ScaleFactorForDepth");
    const QString ScaleTypeForDepth ("ScaleTypeForDepth");
    const QString ScaleDepth ("ScaleDepth");
    const QString ScalingParent ("ScalingParent");
    const QString EventLogType ("EventLogType");
    const QString EventLogDate ("EventLogDate");
    const QString EventLogCode ("EventLogCode");
    const QString EventLogSourceName ("EventLogSourceName");
    const QString EventLogMessage ("EventLogMessage");
    const QString AcquisitionGroup ("AcquisitionGroup");
    const QString CameraImageAcquisitionTime ("CameraImageAcquisitionTime");
    const QString CameraValidBitsPerPixel ("CameraValidBitsPerPixel");
    const QString MonoReferenceLow ("MonoReferenceLow");
    const QString MonoReferenceHigh ("MonoReferenceHigh");
    const QString RedReferenceLow ("RedReferenceLow");
    const QString RedReferenceHigh ("RedReferenceHigh");
    const QString GreenReferenceLow ("GreenReferenceLow");
    const QString GreenReferenceHigh ("GreenReferenceHigh");
    const QString BlueReferenceLow ("BlueReferenceLow");
    const QString BlueReferenceHigh ("BlueReferenceHigh");
    const QString GrabberName ("GrabberName");
    const QString CameraName ("CameraName");
    const QString CameraTriggerSignalType ("CameraTriggerSignalType");
    const QString CameraTriggerEnable ("CameraTriggerEnable");
    const QString GrabberTimeout ("GrabberTimeout");
    const QString AcquisitionTimeInDouble ("AcquisitionTimeInDouble");
    const QString MultiChannelEnabled ("MultiChannelEnabled");
    const QString MultiChannelColor ("MultiChannelColor");
    const QString MultiChannelWeight ("MultiChannelWeight");
    const QString MultiChannelName ("MultiChannelName");
    const QString DocumentInformationGroup ("DocumentInformationGroup");
    const QString DocumentTitle ("DocumentTitle");
    const QString DocumentAuthor ("DocumentAuthor");
    const QString DocumentKeywords ("DocumentKeywords");
    const QString DocumentComments ("DocumentComments");
    const QString DocumentSampleID ("DocumentSampleID");
    const QString DocumentSubject ("DocumentSubject");
    const QString RevisionNumber ("RevisionNumber");
    const QString DocumentPath ("DocumentPath");
    const QString FileLink ("FileLink");
    const QString DocumentType ("DocumentType");
    const QString FileMedium ("FileMedium");
    const QString FileID ("FileID");
    const QString DocumentFileName ("DocumentFileName");
    const QString FileDate ("FileDate");
    const QString FileSize ("FileSize");
    const QString DocumentName ("DocumentName");
    const QString FileAttributes ("FileAttributes");
    const QString ProjectGroup ("ProjectGroup");
    const QString Date ("Date");
    const QString DocumentLastSavedBy ("DocumentLastSavedBy");
    const QString UserCompany ("UserCompany");
    const QString UserCompanyLogo ("UserCompanyLogo");
    const QString Image ("Image");
    const QString UserId ("UserId");
    const QString UserName ("UserName");
    const QString UserCity ("UserCity");
    const QString UserAddress ("UserAddress");
    const QString UserState ("UserState");
    const QString UserPhone ("UserPhone");
    const QString UserFax ("UserFax");
    const QString Objective ("Objective");
    const QString Optovar ("Optovar");
    const QString Reflector ("Reflector");
    const QString CondenserContrast ("CondenserContrast");
    const QString TransmissionFilter1 ("TransmissionFilter1");
    const QString TransmittedLightFilter1 ("TransmittedLightFilter1");
    const QString TransmissionFilter2 ("TransmissionFilter2");
    const QString TransmittedLightFilter2 ("TransmittedLightFilter2");
    const QString InternalShutter ("InternalShutter");
    const QString ReflectedLightShutter ("ReflectedLightShutter");
    const QString CondenserFrontlens ("CondenserFrontlens");
    const QString ExcitationFilter ("ExcitationFilter");
    const QString TransmittedLightFieldstop ("TransmittedLightFieldstop");
    const QString ReflectedLightAperture ("ReflectedLightAperture");
    const QString CondenserNA ("CondenserNA");
    const QString LightPath ("LightPath");
    const QString HalogenLampOn ("HalogenLampOn");
    const QString HalogenLampMode ("HalogenLampMode");
    const QString HalogenLampVoltage ("HalogenLampVoltage");
    const QString FluoLampMode ("FluoLampMode");
    const QString FluoLampIntensity ("FluoLampIntensity");
    const QString LightmanagerEnabled ("LightmanagerEnabled");
    const QString FocusPosition ("FocusPosition");
    const QString ImageCoordinateU ("ImageCoordinateU");
    //const QString StageXPosition ("StageXPosition");
    const QString ImageCoordinateV ("ImageCoordinateV");
    //const QString StageYPosition ("StageYPosition");
    const QString MicroscopeName ("MicroscopeName");
    const QString ObjectiveMagnification ("ObjectiveMagnification");
    const QString ObjectiveNA ("ObjectiveNA");
    const QString MicroscopeIllumination ("MicroscopeIllumination");
    const QString ExtraShutter1 ("ExtraShutter1");
    const QString ExtraShutter2 ("ExtraShutter2");
    const QString ExtraShutter3 ("ExtraShutter3");
    const QString ExtraFilter1 ("ExtraFilter1");
    const QString ExtraFilter2 ("ExtraFilter2");
    const QString ParfocalCorrection ("ParfocalCorrection");
    const QString ExtraShutter4 ("ExtraShutter4");
    const QString ExtraShutter5 ("ExtraShutter5");
    const QString ExtraShutter6 ("ExtraShutter6");
    const QString ExtraFilter3 ("ExtraFilter3");
    const QString ExtraFilter4 ("ExtraFilter4");
    const QString ObjectivePosition ("ObjectivePosition");
    const QString ObjectiveContrastMethod ("ObjectiveContrastMethod");
    const QString ObjectiveImmersionType ("ObjectiveImmersionType");
    const QString ReflectorPosition ("ReflectorPosition");
    const QString TransmissionFilter1Position ("TransmissionFilter1Position");
    const QString TransmittedLightFilter1Position ("TransmittedLightFilter1Position");
    const QString TransmissionFilter2Position ("TransmissionFilter2Position");
    const QString TransmittedLightFilter2Position ("TransmittedLightFilter2Position");
    const QString ExcitationFilterPosition ("ExcitationFilterPosition");
    const QString LampMirrorPosition ("LampMirrorPosition");
    const QString ExtraFilter1Position ("ExtraFilter1Position");
    const QString ExtraFilter2Position ("ExtraFilter2Position");
    const QString ExtraFilter3Position ("ExtraFilter3Position");
    const QString ExtraFilter4Position ("ExtraFilter4Position");
    const QString LightmanagerMode ("LightmanagerMode");
    const QString HalogenLampCalibrated ("HalogenLampCalibrated");
    const QString CondenserNAGoSpeed ("CondenserNAGoSpeed");
    const QString TransmittedLightFieldstopGoSpeed ("TransmittedLightFieldstopGoSpeed");
    const QString OptovarGoSpeed ("OptovarGoSpeed");
    const QString FocusCalibrated ("FocusCalibrated");
    const QString FocusBasicPosition ("FocusBasicPosition");
    const QString FocusPower ("FocusPower");
    const QString FocusBacklash ("FocusBacklash");
    const QString FocusMeasurementOrigin ("FocusMeasurementOrigin");
    const QString FocusMeasurementDistance ("FocusMeasurementDistance");
    const QString FocusSpeed ("FocusSpeed");
    const QString FocusGoSpeed ("FocusGoSpeed");
    const QString FocusStepDistance ("FocusStepDistance");
    const QString FocusInitPosition ("FocusInitPosition");
    const QString StageCalibrated ("StageCalibrated");
    const QString StagePower ("StagePower");
    const QString StageXBacklash ("StageXBacklash");
    const QString StageYBacklash ("StageYBacklash");
    const QString StageXSpeed ("StageXSpeed");
    const QString StageYSpeed ("StageYSpeed");
    const QString StageSpeed ("StageSpeed");
    const QString StageXGoSpeed ("StageXGoSpeed");
    const QString StageYGoSpeed ("StageYGoSpeed");
    const QString StageXStepDistance ("StageXStepDistance");
    const QString StageYStepDistance ("StageYStepDistance");
    const QString StageXInitPosition ("StageXInitPosition");
    const QString StageYInitPosition ("StageYInitPosition");
    const QString MicroscopeMagnification ("MicroscopeMagnification");
    const QString ReflectorMagnification ("ReflectorMagnification");
    const QString LampMirrorSelection ("LampMirrorSelection");
    const QString FocusDepth ("FocusDepth");
    const QString MicroscopeType ("MicroscopeType");
    const QString ObjectiveWorkingDistance ("ObjectiveWorkingDistance");
    const QString ReflectedLightApertureGoSpeed ("ReflectedLightApertureGoSpeed");
    const QString ExternalShutter ("ExternalShutter");
    const QString ObjectiveImmersionStopActive ("ObjectiveImmersionStopActive");
    const QString FocusStartSpeed ("FocusStartSpeed");
    const QString FocusAcceleration ("FocusAcceleration");
    const QString ReflectedLightFieldstop ("ReflectedLightFieldstop");
    const QString ReflectedLightFieldstopGoSpeed ("ReflectedLightFieldstopGoSpeed");
    const QString ReflectedLightFilter1 ("ReflectedLightFilter1");
    const QString ReflectedLightFilter2 ("ReflectedLightFilter2");
    const QString ReflectedLightFilter1Position ("ReflectedLightFilter1Position");
    const QString ReflectedLightFilter2Position ("ReflectedLightFilter2Position");
    const QString TransmittedLightAttenuator ("TransmittedLightAttenuator");
    const QString ReflectedLightAttenuator ("ReflectedLightAttenuator");
    const QString TransmittedLightShutter ("TransmittedLightShutter");
    const QString TransmittedLightAttenuatorGoSpeed ("TransmittedLightAttenuatorGoSpeed");
    const QString ReflectedLightAttenuatorGoSpeed ("ReflectedLightAttenuatorGoSpeed");
    const QString ApotomeFocusPosition ("ApotomeFocusPosition");
    const QString ApotomeFocusGoSpeed ("ApotomeFocusGoSpeed");
    const QString ApotomePhasePosition ("ApotomePhasePosition");
    const QString ApotomeSliderPosition ("ApotomeSliderPosition");
    const QString ApotomeGridLinesPerMillimeter ("ApotomeGridLinesPerMillimeter");
    const QString ApotomeWobbleMinPosition ("ApotomeWobbleMinPosition");
    const QString ApotomeWobbleMaxPosition ("ApotomeWobbleMaxPosition");
    const QString ApotomeWobbleSpeed ("ApotomeWobbleSpeed");
    const QString TransmittedLightVirtualFilterPosition ("TransmittedLightVirtualFilterPosition");
    const QString TransmittedLightVirtualFilter ("TransmittedLightVirtualFilter");
    const QString ReflectedLightVirtualFilterPosition ("ReflectedLightVirtualFilterPosition");
    const QString ReflectedLightVirtualFilter ("ReflectedLightVirtualFilter");
    const QString ReflectedLightHALMode ("ReflectedLightHALMode");
    const QString ReflectedLightHALVoltage ("ReflectedLightHALVoltage");
    const QString ReflectedLightHALColourTemperature ("ReflectedLightHALColourTemperature");
    const QString ContrastmanagerMode ("ContrastmanagerMode");
    const QString DazzleProtection ("DazzleProtection");
    const QString StageXCalibrated ("StageXCalibrated");
    const QString StageYCalibrated ("StageYCalibrated");
    const QString StageXPower ("StageXPower");
    const QString StageYPower ("StageYPower");
    const QString StageXStartSpeed ("StageXStartSpeed");
    const QString StageYStartSpeed ("StageYStartSpeed");
    const QString StageXAcceleration ("StageXAcceleration");
    const QString StageYAcceleration ("StageYAcceleration");
    const QString StageStartSpeed ("StageStartSpeed");
    const QString StageAcceleration ("StageAcceleration");
    const QString Zoom ("Zoom");
    const QString ZoomGoSpeed ("ZoomGoSpeed");
    const QString LightZoom ("LightZoom");
    const QString LightZoomGoSpeed ("LightZoomGoSpeed");
    const QString LightZoomCoupled ("LightZoomCoupled");
    const QString TransmittedLightHALMode ("TransmittedLightHALMode");
    const QString TransmittedLightHALVoltage ("TransmittedLightHALVoltage");
    const QString TransmittedLightHALColourTemperature ("TransmittedLightHALColourTemperature");
    const QString ReflectedLightCLMode ("ReflectedLightCLMode");
    const QString ReflectedLightCLIntensity ("ReflectedLightCLIntensity");
    const QString ReflectedLightCLColourTemperature ("ReflectedLightCLColourTemperature");
    const QString TransmittedLightCLMode ("TransmittedLightCLMode");
    const QString TransmittedLightCLIntensity ("TransmittedLightCLIntensity");
    const QString TransmittedLightCLColourTemperature ("TransmittedLightCLColourTemperature");
    const QString InfinitySpaceChangerPosition ("InfinitySpaceChangerPosition");
    const QString SidePortPercent ("SidePortPercent");
    const QString TwoTvVisCamChangerPosition ("TwoTvVisCamChangerPosition");
    const QString OcularPercent ("OcularPercent");
    const QString TwoTvCamerasChangerPosition ("TwoTvCamerasChangerPosition");
    const QString TopPortPercent ("TopPortPercent");
    const QString OcularShutter ("OcularShutter");
    const QString TwoTvCamerasChangerCube ("TwoTvCamerasChangerCube");
    const QString LightWaveLength ("LightWaveLength");
    const QString OcularMagnification ("OcularMagnification");
    const QString CameraAdapterMagnification ("CameraAdapterMagnification");
    const QString MicroscopePort ("MicroscopePort");
    const QString OcularTotalMagnification ("OcularTotalMagnification");
    const QString FieldOfView ("FieldOfView");
    const QString Ocular ("Ocular");
    const QString CameraAdapter ("CameraAdapter");
    const QString StageJoystickEnabled ("StageJoystickEnabled");
    const QString ContrastmanagerContrastMethod ("ContrastmanagerContrastMethod");
    const QString StageXJoystickEnabled ("StageXJoystickEnabled");
    const QString StageYJoystickEnabled ("StageYJoystickEnabled");
    const QString CameraFrameLeft ("CameraFrameLeft");
    const QString CameraFrameTop ("CameraFrameTop");
    const QString CameraFrameWidth ("CameraFrameWidth");
    const QString CameraFrameHeight ("CameraFrameHeight");
    const QString CameraFrameBinning ("CameraFrameBinning");
    const QString CameraFrameFull ("CameraFrameFull");
    const QString CameraFramePixelDistance ("CameraFramePixelDistance");
    const QString DataFormatUseScaling ("DataFormatUseScaling");
    const QString CameraFrameImageOrientation ("CameraFrameImageOrientation");
    const QString MeteorChannelInput ("MeteorChannelInput");
    const QString MeteorChannelSync ("MeteorChannelSync");
    const QString CameraWhiteBalanceRed ("CameraWhiteBalanceRed");
    const QString CameraWhiteBalanceGreen ("CameraWhiteBalanceGreen");
    const QString CameraWhiteBalanceBlue ("CameraWhiteBalanceBlue");
    const QString CameraFrameScalingFactor ("CameraFrameScalingFactor");
    const QString MeteorCameraType ("MeteorCameraType");
    const QString CameraExposureTimeValue ("CameraExposureTimeValue");
    const QString CameraExposureTimeAutoCalculate ("CameraExposureTimeAutoCalculate");
    const QString MeteorGainValue ("MeteorGainValue");
    const QString MeteorGainAutomatic ("MeteorGainAutomatic");
    const QString MeteorAdjustHue ("MeteorAdjustHue");
    const QString MeteorAdjustSaturation ("MeteorAdjustSaturation");
    const QString MeteorAdjustRedLow ("MeteorAdjustRedLow");
    const QString MeteorAdjustGreenLow ("MeteorAdjustGreenLow");
    const QString MeteorAdjustBlueLow ("MeteorAdjustBlueLow");
    const QString MeteorAdjustRedHigh ("MeteorAdjustRedHigh");
    const QString MeteorAdjustGreenHigh ("MeteorAdjustGreenHigh");
    const QString MeteorAdjustBlueHigh ("MeteorAdjustBlueHigh");
    const QString MeteorAdjustWhiteRefEnable ("MeteorAdjustWhiteRefEnable");
    const QString CameraExposureTimeCalculationControl ("CameraExposureTimeCalculationControl");
    const QString AxioCamFadingCorrectionEnable ("AxioCamFadingCorrectionEnable");
    const QString AxioCamSuspendLiveTimeout ("AxioCamSuspendLiveTimeout");
    const QString CameraLiveImage ("CameraLiveImage");
    const QString CameraLiveEnabled ("CameraLiveEnabled");
    const QString LiveImageSyncObjectName ("LiveImageSyncObjectName");
    const QString CameraLiveSpeed ("CameraLiveSpeed");
    const QString CameraImage ("CameraImage");
    const QString CameraImageWidth ("CameraImageWidth");
    const QString CameraImageHeight ("CameraImageHeight");
    const QString CameraImagePixelType ("CameraImagePixelType");
    const QString CameraImageShMemoryName ("CameraImageShMemoryName");
    const QString CameraLiveImageWidth ("CameraLiveImageWidth");
    const QString CameraLiveImageHeight ("CameraLiveImageHeight");
    const QString CameraLiveImagePixelType ("CameraLiveImagePixelType");
    const QString CameraLiveImageShMemoryName ("CameraLiveImageShMemoryName");
    const QString CameraLiveMaximumSpeed ("CameraLiveMaximumSpeed");
    const QString CameraLiveBinning ("CameraLiveBinning");
    const QString CameraLiveGainValue ("CameraLiveGainValue");
    const QString CameraLiveExposureTimeValue ("CameraLiveExposureTimeValue");
    const QString CameraLiveScalingFactor ("CameraLiveScalingFactor");
    const QString CameraCoAcqFastMode ("CameraCoAcqFastMode");
    const QString ImageIndexU ("ImageIndexU");
    const QString ImageIndexV ("ImageIndexV");
    const QString ImageIndexZ ("ImageIndexZ");
    const QString ImageIndexC ("ImageIndexC");
    const QString ImageIndexT ("ImageIndexT");
    const QString ImageIndexP ("ImageIndexP");
    const QString ImageIndexA ("ImageIndexA");
    const QString ImageCountP ("ImageCountP");
    const QString ImageCountA ("ImageCountA");
    const QString ImageIndexS ("ImageIndexS");
    const QString ImageIndexRaw ("ImageIndexRaw");
    const QString ImageCountZ ("ImageCountZ");
    const QString ImageCountC ("ImageCountC");
    const QString ImageCountT ("ImageCountT");
    const QString ImageCountU ("ImageCountU");
    const QString ImageCountV ("ImageCountV");
    const QString ImageCountS ("ImageCountS");
    const QString ImageOrgCoordinateU ("ImageOrgCoordinateU");
    const QString ImageOrgCoordinateV ("ImageOrgCoordinateV");
    const QString LayerDrawFlags ("LayerDrawFlags");
    const QString JobGroup ("JobGroup");
    const QString JobName ("JobName");
    const QString JobInfo ("JobInfo");
    const QString JobProgress ("JobProgress");
    const QString JobStatus ("JobStatus");
    const QString JobId ("JobId");
    const QString JobRemainingTime ("JobRemainingTime");

    const QString RelFocusPosition1 ("RelFocusPosition1");
    const QString RelFocusPosition2 ("RelFocusPosition2");
    const QString RelFocusPosition ("RelFocusPosition");
    const QString SidePortTurretposition ("SidePortTurretposition");
    const QString SidePortLeftPercent ("SidePortLeftPercent");
    const QString SidePortRightPercent ("SidePortRightPercent");
    const QString BasePortSliderPortPercent ("BasePortSliderPortPercent");
    const QString SidePortLeftFunction ("SidePortLeftFunction");
    const QString SidePortRightFunction ("SidePortRightFunction");
    const QString BasePortSliderPortFunction ("BasePortSliderPortFunction");
    const QString SidePortLightPath ("SidePortLightPath");
    const QString SidePortLightPathID ("SidePortLightPathID");
    const QString ObjectiveID ("ObjectiveID");
    const QString ReflectorID ("ReflectorID");


  }
}
#endif /* ZEISSTAGMAPPING_H_ */
